sonar.projectKey=nodejsmysql
sonar.projectName=nodejsmysql

sonar.sources=.

# IMPORTANT FIX
sonar.java.binaries=.

# Ignore unnecessary directories
sonar.exclusions=node_modules/**,.scannerwork/**,.git/**

# optional but recommended
sonar.sourceEncoding=UTF-8
